prompt --application/pages/page_00033
begin
--   Manifest
--     PAGE: 00033
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.9'
,p_default_workspace_id=>71533046799736978747
,p_default_application_id=>24839
,p_default_id_offset=>9071155675752509
,p_default_owner=>'WKSP_DTESC'
);
wwv_flow_imp_page.create_page(
 p_id=>33
,p_name=>'borrame'
,p_alias=>'BORRAME'
,p_step_title=>'borrame'
,p_autocomplete_on_off=>'OFF'
,p_page_template_options=>'#DEFAULT#'
,p_protection_level=>'C'
,p_page_component_map=>'18'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(44783569117796563731)
,p_plug_name=>'borrame'
,p_region_template_options=>'#DEFAULT#:t-IRR-region--hideHeader js-addHiddenHeadingRoleDesc'
,p_plug_template=>2100526641005906379
,p_plug_display_sequence=>10
,p_query_type=>'TABLE'
,p_query_table=>'SGT_ENLACES_TRAMOS'
,p_include_rowid_column=>false
,p_plug_source_type=>'NATIVE_IR'
,p_prn_page_header=>'borrame'
);
wwv_flow_imp_page.create_worksheet(
 p_id=>wwv_flow_imp.id(44783569256461563731)
,p_name=>'borrame'
,p_max_row_count_message=>'The maximum row count for this report is #MAX_ROW_COUNT# rows.  Please apply a filter to reduce the number of records in your query.'
,p_no_data_found_message=>'No data found.'
,p_pagination_type=>'ROWS_X_TO_Y'
,p_pagination_display_pos=>'BOTTOM_RIGHT'
,p_report_list_mode=>'TABS'
,p_lazy_loading=>false
,p_show_detail_link=>'N'
,p_show_notify=>'Y'
,p_download_formats=>'CSV:HTML:XLSX:PDF'
,p_enable_mail_download=>'Y'
,p_owner=>'DTEMSC6'
,p_internal_uid=>44783569256461563731
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(44783576228615563986)
,p_db_column_name=>'ID'
,p_display_order=>0
,p_is_primary_key=>'Y'
,p_column_identifier=>'A'
,p_column_label=>'ID'
,p_column_type=>'NUMBER'
,p_display_text_as=>'HIDDEN_ESCAPE_SC'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(44783576617007563986)
,p_db_column_name=>'NOMBRE'
,p_display_order=>2
,p_column_identifier=>'B'
,p_column_label=>'Nombre'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(44783577064972563987)
,p_db_column_name=>'ENLACE_ID'
,p_display_order=>3
,p_column_identifier=>'C'
,p_column_label=>'Enlace'
,p_column_type=>'STRING'
,p_display_text_as=>'LOV_ESCAPE_SC'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_rpt_named_lov=>wwv_flow_imp.id(43769668587515608859)
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(44783577475494563987)
,p_db_column_name=>'ENLACE_NOMBRE'
,p_display_order=>4
,p_column_identifier=>'D'
,p_column_label=>'Enlace Nombre'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(44783577815853563988)
,p_db_column_name=>'SERVICIO_ID'
,p_display_order=>5
,p_column_identifier=>'E'
,p_column_label=>'Servicio'
,p_column_type=>'STRING'
,p_display_text_as=>'LOV_ESCAPE_SC'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_rpt_named_lov=>wwv_flow_imp.id(44132876898299381933)
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(44783578207439563989)
,p_db_column_name=>'SERVICIO_NOMBRE'
,p_display_order=>6
,p_column_identifier=>'F'
,p_column_label=>'Servicio Nombre'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(44783578650253563989)
,p_db_column_name=>'LADO_ID'
,p_display_order=>7
,p_column_identifier=>'G'
,p_column_label=>'Lado'
,p_column_type=>'STRING'
,p_display_text_as=>'LOV_ESCAPE_SC'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_rpt_named_lov=>wwv_flow_imp.id(202814172118838557260)
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(44783579025455563990)
,p_db_column_name=>'EQUIPO_A_ID'
,p_display_order=>8
,p_column_identifier=>'H'
,p_column_label=>'Equipo A'
,p_column_type=>'STRING'
,p_display_text_as=>'LOV_ESCAPE_SC'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_rpt_named_lov=>wwv_flow_imp.id(16838483136411509974)
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(44783579420932563990)
,p_db_column_name=>'EQUIPO_A_NOMBRE'
,p_display_order=>9
,p_column_identifier=>'I'
,p_column_label=>'Equipo A Nombre'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(44783579828135563991)
,p_db_column_name=>'INTERFAZ_A_ID'
,p_display_order=>10
,p_column_identifier=>'J'
,p_column_label=>'Interfaz A'
,p_column_type=>'STRING'
,p_display_text_as=>'LOV_ESCAPE_SC'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_rpt_named_lov=>wwv_flow_imp.id(43769671252068608862)
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(44783580254219563991)
,p_db_column_name=>'INTERFAZ_A_NOMBRE'
,p_display_order=>11
,p_column_identifier=>'K'
,p_column_label=>'Interfaz A Nombre'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(44783580636895563991)
,p_db_column_name=>'EQUIPO_B_ID'
,p_display_order=>12
,p_column_identifier=>'L'
,p_column_label=>'Equipo B'
,p_column_type=>'STRING'
,p_display_text_as=>'LOV_ESCAPE_SC'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_rpt_named_lov=>wwv_flow_imp.id(16838483136411509974)
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(44783581084695563992)
,p_db_column_name=>'EQUIPO_B_NOMBRE'
,p_display_order=>13
,p_column_identifier=>'M'
,p_column_label=>'Equipo B Nombre'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(44783581431419563992)
,p_db_column_name=>'INTERFAZ_B_ID'
,p_display_order=>14
,p_column_identifier=>'N'
,p_column_label=>'Interfaz B'
,p_column_type=>'STRING'
,p_display_text_as=>'LOV_ESCAPE_SC'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_rpt_named_lov=>wwv_flow_imp.id(43769671252068608862)
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(44783581887366563992)
,p_db_column_name=>'INTERFAZ_B_NOMBRE'
,p_display_order=>15
,p_column_identifier=>'O'
,p_column_label=>'Interfaz B Nombre'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(44783582291097563993)
,p_db_column_name=>'CREADO_POR'
,p_display_order=>16
,p_column_identifier=>'P'
,p_column_label=>'Creado Por'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(44783582648729563993)
,p_db_column_name=>'CREADO_EL'
,p_display_order=>17
,p_column_identifier=>'Q'
,p_column_label=>'Creado El'
,p_column_type=>'DATE'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(44783583077955563994)
,p_db_column_name=>'ACTUALIZADO_POR'
,p_display_order=>18
,p_column_identifier=>'R'
,p_column_label=>'Actualizado Por'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(44783583436829563994)
,p_db_column_name=>'ACTUALIZADO_EL'
,p_display_order=>19
,p_column_identifier=>'S'
,p_column_label=>'Actualizado El'
,p_column_type=>'DATE'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_rpt(
 p_id=>wwv_flow_imp.id(44783603708299564992)
,p_application_user=>'APXWS_DEFAULT'
,p_report_seq=>10
,p_report_alias=>'447836038'
,p_status=>'PUBLIC'
,p_is_default=>'Y'
,p_report_columns=>'ID:NOMBRE:ENLACE_ID:ENLACE_NOMBRE:SERVICIO_ID:SERVICIO_NOMBRE:LADO_ID:EQUIPO_A_ID:EQUIPO_A_NOMBRE:INTERFAZ_A_ID:INTERFAZ_A_NOMBRE:EQUIPO_B_ID:EQUIPO_B_NOMBRE:INTERFAZ_B_ID:INTERFAZ_B_NOMBRE:CREADO_POR:CREADO_EL:ACTUALIZADO_POR:ACTUALIZADO_EL'
);
wwv_flow_imp.component_end;
end;
/
