prompt --application/pages/page_00036
begin
--   Manifest
--     PAGE: 00036
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.9'
,p_default_workspace_id=>71533046799736978747
,p_default_application_id=>24839
,p_default_id_offset=>9071155675752509
,p_default_owner=>'WKSP_DTESC'
);
wwv_flow_imp_page.create_page(
 p_id=>36
,p_name=>'SGT_LST_ENLACES_FO_2'
,p_alias=>'SGT-ENLACES-FO-2'
,p_step_title=>'Enlaces FO'
,p_autocomplete_on_off=>'OFF'
,p_page_template_options=>'#DEFAULT#'
,p_protection_level=>'C'
,p_page_component_map=>'18'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(43997218799581517994)
,p_plug_name=>'Breadcrumb'
,p_region_template_options=>'#DEFAULT#:t-BreadcrumbRegion--useBreadcrumbTitle'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>2531463326621247859
,p_plug_display_sequence=>10
,p_plug_display_point=>'REGION_POSITION_01'
,p_menu_id=>wwv_flow_imp.id(197180072443235446203)
,p_plug_source_type=>'NATIVE_BREADCRUMB'
,p_menu_template_id=>4072363345357175094
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(43997219426089517996)
,p_plug_name=>'SGT_ENLACES_FO_2'
,p_title=>'Enlaces FO'
,p_region_template_options=>'#DEFAULT#:t-IRR-region--hideHeader js-addHiddenHeadingRoleDesc'
,p_plug_template=>2100526641005906379
,p_plug_display_sequence=>10
,p_query_type=>'TABLE'
,p_query_table=>'SGT_ENLACES_FO'
,p_query_order_by_type=>'STATIC'
,p_query_order_by=>'ID DESC'
,p_include_rowid_column=>false
,p_plug_source_type=>'NATIVE_IR'
,p_prn_content_disposition=>'ATTACHMENT'
,p_prn_units=>'MILLIMETERS'
,p_prn_paper_size=>'A4'
,p_prn_width=>297
,p_prn_height=>210
,p_prn_orientation=>'HORIZONTAL'
,p_prn_page_header=>'Enlaces FO'
,p_prn_page_header_font_color=>'#000000'
,p_prn_page_header_font_family=>'Helvetica'
,p_prn_page_header_font_weight=>'normal'
,p_prn_page_header_font_size=>'12'
,p_prn_page_footer_font_color=>'#000000'
,p_prn_page_footer_font_family=>'Helvetica'
,p_prn_page_footer_font_weight=>'normal'
,p_prn_page_footer_font_size=>'12'
,p_prn_header_bg_color=>'#EEEEEE'
,p_prn_header_font_color=>'#000000'
,p_prn_header_font_family=>'Helvetica'
,p_prn_header_font_weight=>'bold'
,p_prn_header_font_size=>'10'
,p_prn_body_bg_color=>'#FFFFFF'
,p_prn_body_font_color=>'#000000'
,p_prn_body_font_family=>'Helvetica'
,p_prn_body_font_weight=>'normal'
,p_prn_body_font_size=>'10'
,p_prn_border_width=>.5
,p_prn_page_header_alignment=>'CENTER'
,p_prn_page_footer_alignment=>'CENTER'
,p_prn_border_color=>'#666666'
);
wwv_flow_imp_page.create_worksheet(
 p_id=>wwv_flow_imp.id(87993675430956945820)
,p_max_row_count=>'1000000'
,p_pagination_type=>'ROWS_X_TO_Y'
,p_pagination_display_pos=>'BOTTOM_RIGHT'
,p_report_list_mode=>'TABS'
,p_lazy_loading=>false
,p_show_detail_link=>'C'
,p_show_notify=>'Y'
,p_download_formats=>'CSV:HTML:XLSX:PDF'
,p_enable_mail_download=>'Y'
,p_detail_link=>'f?p=&APP_ID.:27:&SESSION.::&DEBUG.::P27_ID:#ID#'
,p_detail_link_text=>'<span role="img" aria-label="Edit" class="fa fa-edit" title="Edit"></span>'
,p_owner=>'DTEMSC6'
,p_internal_uid=>87993675430956945820
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87993675588645945821)
,p_db_column_name=>'ID'
,p_display_order=>10
,p_is_primary_key=>'Y'
,p_column_identifier=>'A'
,p_column_label=>'Id'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87993675655549945822)
,p_db_column_name=>'NOMBRE'
,p_display_order=>20
,p_column_identifier=>'B'
,p_column_label=>'Nombre'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87993675737861945823)
,p_db_column_name=>'SITIO_ID_A'
,p_display_order=>30
,p_column_identifier=>'C'
,p_column_label=>'Sitio Id A'
,p_column_type=>'NUMBER'
,p_display_text_as=>'LOV_ESCAPE_SC'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_rpt_named_lov=>wwv_flow_imp.id(202814172118838557260)
,p_rpt_show_filter_lov=>'1'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87993675854786945824)
,p_db_column_name=>'EQUIPO_ID_A'
,p_display_order=>40
,p_column_identifier=>'D'
,p_column_label=>'Equipo Id A'
,p_column_type=>'NUMBER'
,p_display_text_as=>'LOV_ESCAPE_SC'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_rpt_named_lov=>wwv_flow_imp.id(16838483136411509974)
,p_rpt_show_filter_lov=>'1'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87993675999009945825)
,p_db_column_name=>'SITIO_ID_B'
,p_display_order=>50
,p_column_identifier=>'E'
,p_column_label=>'Sitio Id B'
,p_column_type=>'NUMBER'
,p_display_text_as=>'LOV_ESCAPE_SC'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_rpt_named_lov=>wwv_flow_imp.id(202814172118838557260)
,p_rpt_show_filter_lov=>'1'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87993676079097945826)
,p_db_column_name=>'EQUIPO_ID_B'
,p_display_order=>60
,p_column_identifier=>'F'
,p_column_label=>'Equipo Id B'
,p_column_type=>'NUMBER'
,p_display_text_as=>'LOV_ESCAPE_SC'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_rpt_named_lov=>wwv_flow_imp.id(16838483136411509974)
,p_rpt_show_filter_lov=>'1'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87993676160269945827)
,p_db_column_name=>unistr('CERTIFICACI\00D3N')
,p_display_order=>70
,p_column_identifier=>'G'
,p_column_label=>unistr('Certificaci\00F3n')
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87993676274367945828)
,p_db_column_name=>'UNIDAD_MEDIDA'
,p_display_order=>80
,p_column_identifier=>'H'
,p_column_label=>'Unidad Medida'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87993676395172945829)
,p_db_column_name=>'ABS_LONGITUD'
,p_display_order=>90
,p_column_identifier=>'I'
,p_column_label=>'Abs Longitud'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87993676417070945830)
,p_db_column_name=>'CANTIDAD_DE_PELOS'
,p_display_order=>100
,p_column_identifier=>'J'
,p_column_label=>'Cantidad De Pelos'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87993676526864945831)
,p_db_column_name=>'TIPO_DE_FO'
,p_display_order=>110
,p_column_identifier=>'K'
,p_column_label=>'Tipo De Fo'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87993676696214945832)
,p_db_column_name=>'TIPO'
,p_display_order=>120
,p_column_identifier=>'L'
,p_column_label=>'Tipo'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87993676789763945833)
,p_db_column_name=>'LT'
,p_display_order=>130
,p_column_identifier=>'M'
,p_column_label=>'Lt'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87993676811914945834)
,p_db_column_name=>'CONECTOR'
,p_display_order=>140
,p_column_identifier=>'N'
,p_column_label=>'Conector'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87993676952879945835)
,p_db_column_name=>'ESTADO'
,p_display_order=>150
,p_column_identifier=>'O'
,p_column_label=>'Estado'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87993677005322945836)
,p_db_column_name=>'COMENTARIOS'
,p_display_order=>160
,p_column_identifier=>'P'
,p_column_label=>'Comentarios'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87993677198981945837)
,p_db_column_name=>unistr('PROYECTO_DE_IMPLEMENTACI\00D3N')
,p_display_order=>170
,p_column_identifier=>'Q'
,p_column_label=>unistr('Proyecto De Implementaci\00F3n')
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87993677202371945838)
,p_db_column_name=>unistr('FECHA_IMPLEMENTACI\00D3N')
,p_display_order=>180
,p_column_identifier=>'R'
,p_column_label=>unistr('Fecha Implementaci\00F3n')
,p_column_type=>'DATE'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87993677353722945839)
,p_db_column_name=>'UNIDAD_ENCARGADA_ACTUAL'
,p_display_order=>190
,p_column_identifier=>'S'
,p_column_label=>'Unidad Encargada Actual'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87993677413596945840)
,p_db_column_name=>'CREADO_POR'
,p_display_order=>200
,p_column_identifier=>'T'
,p_column_label=>'Creado Por'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87993677501320945841)
,p_db_column_name=>'CREADO_EL'
,p_display_order=>210
,p_column_identifier=>'U'
,p_column_label=>'Creado El'
,p_column_type=>'DATE'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87993677644684945842)
,p_db_column_name=>'ACTUALIZADO_POR'
,p_display_order=>220
,p_column_identifier=>'V'
,p_column_label=>'Actualizado Por'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87993677741993945843)
,p_db_column_name=>'ACTUALIZADO_EL'
,p_display_order=>230
,p_column_identifier=>'W'
,p_column_label=>'Actualizado El'
,p_column_type=>'DATE'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87993677841492945844)
,p_db_column_name=>'TIPO_CABLE'
,p_display_order=>240
,p_column_identifier=>'X'
,p_column_label=>'Tipo Cable'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87993677984525945845)
,p_db_column_name=>'TIPO_TENDIDO'
,p_display_order=>250
,p_column_identifier=>'Y'
,p_column_label=>'Tipo Tendido'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_rpt(
 p_id=>wwv_flow_imp.id(87999151971855747250)
,p_application_user=>'APXWS_DEFAULT'
,p_report_seq=>10
,p_report_alias=>'879991520'
,p_status=>'PUBLIC'
,p_is_default=>'Y'
,p_report_columns=>unistr('ID:NOMBRE:SITIO_ID_A:EQUIPO_ID_A:SITIO_ID_B:EQUIPO_ID_B:CERTIFICACI\00D3N:UNIDAD_MEDIDA:CANTIDAD_DE_PELOS:TIPO_DE_FO:TIPO:LT:CONECTOR:ESTADO:COMENTARIOS:PROYECTO_DE_IMPLEMENTACI\00D3N:FECHA_IMPLEMENTACI\00D3N:UNIDAD_ENCARGADA_ACTUAL:CREADO_POR:CREADO_EL:ACTUALIZ')
||'ADO_POR:ACTUALIZADO_EL:TIPO_CABLE:TIPO_TENDIDO:'
,p_sort_column_1=>unistr('CERTIFICACI\00D3N')
,p_sort_direction_1=>'ASC'
);
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(51494080773735384815)
,p_button_sequence=>10
,p_button_plug_id=>wwv_flow_imp.id(43997219426089517996)
,p_button_name=>'CREATE'
,p_button_action=>'REDIRECT_PAGE'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>4072362960822175091
,p_button_is_hot=>'Y'
,p_button_image_alt=>'&APP_TEXT$BTN_CREAR!RAW.'
,p_button_position=>'RIGHT_OF_IR_SEARCH_BAR'
,p_button_redirect_url=>'f?p=&APP_ID.:27:&SESSION.::&DEBUG.:::'
,p_security_scheme=>wwv_flow_imp.id(56843702980053272617)
);
wwv_flow_imp_page.create_page_da_event(
 p_id=>wwv_flow_imp.id(43996537929573508710)
,p_name=>'RefreshRegion'
,p_event_sequence=>10
,p_triggering_element_type=>'REGION'
,p_triggering_region_id=>wwv_flow_imp.id(43997219426089517996)
,p_bind_type=>'bind'
,p_execution_type=>'IMMEDIATE'
,p_bind_event_type=>'apexafterclosedialog'
);
wwv_flow_imp_page.create_page_da_action(
 p_id=>wwv_flow_imp.id(43996538085274508711)
,p_event_id=>wwv_flow_imp.id(43996537929573508710)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_REFRESH'
,p_affected_elements_type=>'REGION'
,p_affected_region_id=>wwv_flow_imp.id(43997219426089517996)
,p_attribute_01=>'N'
);
wwv_flow_imp.component_end;
end;
/
