prompt --application/pages/page_00013
begin
--   Manifest
--     PAGE: 00013
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.9'
,p_default_workspace_id=>71533046799736978747
,p_default_application_id=>24839
,p_default_id_offset=>9071155675752509
,p_default_owner=>'WKSP_DTESC'
);
wwv_flow_imp_page.create_page(
 p_id=>13
,p_name=>'SGT_LST_EQUIPOS'
,p_alias=>'SGT-LST-EQUIPOS'
,p_step_title=>'Lista de equipos'
,p_autocomplete_on_off=>'OFF'
,p_page_template_options=>'#DEFAULT#'
,p_protection_level=>'C'
,p_page_component_map=>'18'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(200805769845760280023)
,p_plug_name=>'SGT_LST_EQUIPOS'
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>2100526641005906379
,p_plug_display_sequence=>10
,p_query_type=>'TABLE'
,p_query_table=>'SGT_EQUIPOS'
,p_query_order_by_type=>'STATIC'
,p_query_order_by=>'ID DESC'
,p_include_rowid_column=>false
,p_plug_source_type=>'NATIVE_IR'
,p_prn_content_disposition=>'ATTACHMENT'
,p_prn_units=>'MILLIMETERS'
,p_prn_paper_size=>'A4'
,p_prn_width=>297
,p_prn_height=>210
,p_prn_orientation=>'HORIZONTAL'
,p_prn_page_header_font_color=>'#000000'
,p_prn_page_header_font_family=>'Helvetica'
,p_prn_page_header_font_weight=>'normal'
,p_prn_page_header_font_size=>'12'
,p_prn_page_footer_font_color=>'#000000'
,p_prn_page_footer_font_family=>'Helvetica'
,p_prn_page_footer_font_weight=>'normal'
,p_prn_page_footer_font_size=>'12'
,p_prn_header_bg_color=>'#EEEEEE'
,p_prn_header_font_color=>'#000000'
,p_prn_header_font_family=>'Helvetica'
,p_prn_header_font_weight=>'bold'
,p_prn_header_font_size=>'10'
,p_prn_body_bg_color=>'#FFFFFF'
,p_prn_body_font_color=>'#000000'
,p_prn_body_font_family=>'Helvetica'
,p_prn_body_font_weight=>'normal'
,p_prn_body_font_size=>'10'
,p_prn_border_width=>.5
,p_prn_page_header_alignment=>'CENTER'
,p_prn_page_footer_alignment=>'CENTER'
,p_prn_border_color=>'#666666'
);
wwv_flow_imp_page.create_worksheet(
 p_id=>wwv_flow_imp.id(87976622166233604112)
,p_max_row_count=>'1000000'
,p_pagination_type=>'ROWS_X_TO_Y'
,p_pagination_display_pos=>'BOTTOM_RIGHT'
,p_report_list_mode=>'TABS'
,p_lazy_loading=>false
,p_show_detail_link=>'C'
,p_show_notify=>'Y'
,p_download_formats=>'CSV:HTML:XLSX:PDF'
,p_enable_mail_download=>'Y'
,p_detail_link=>'f?p=&APP_ID.:14:&SESSION.::&DEBUG.::P14_ID:#ID#'
,p_detail_link_text=>'<span role="img" aria-label="Edit" class="fa fa-edit" title="Edit"></span>'
,p_detail_link_auth_scheme=>wwv_flow_imp.id(56843702980053272617)
,p_owner=>'DTEMSC6'
,p_internal_uid=>87976622166233604112
);
wwv_flow_imp_page.create_worksheet_col_group(
 p_id=>wwv_flow_imp.id(2361631548276199)
,p_name=>'New'
,p_description=>'Prueba'
,p_display_sequence=>10
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87976622230756604113)
,p_db_column_name=>'ID'
,p_display_order=>10
,p_is_primary_key=>'Y'
,p_column_identifier=>'A'
,p_column_label=>'Id'
,p_column_type=>'NUMBER'
,p_display_text_as=>'HIDDEN_ESCAPE_SC'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87976622322586604114)
,p_db_column_name=>'UNIDAD_ENCARGADA'
,p_display_order=>20
,p_column_identifier=>'B'
,p_column_label=>'Unidad Encargada'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87976622415369604115)
,p_db_column_name=>'RACK_ID'
,p_display_order=>30
,p_column_identifier=>'C'
,p_column_label=>'Rack'
,p_column_type=>'NUMBER'
,p_display_text_as=>'LOV_ESCAPE_SC'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_rpt_named_lov=>wwv_flow_imp.id(18965791847251143770)
,p_rpt_show_filter_lov=>'1'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87976622528987604116)
,p_db_column_name=>'U'
,p_display_order=>40
,p_column_identifier=>'D'
,p_column_label=>'U'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87976622646235604117)
,p_db_column_name=>'TIPO_RED'
,p_display_order=>50
,p_column_identifier=>'E'
,p_column_label=>'Tipo Red'
,p_column_type=>'STRING'
,p_display_text_as=>'LOV_ESCAPE_SC'
,p_heading_alignment=>'LEFT'
,p_rpt_named_lov=>wwv_flow_imp.id(17291432086166556461)
,p_rpt_show_filter_lov=>'1'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87976622734897604118)
,p_db_column_name=>'NOMBRE'
,p_display_order=>60
,p_column_identifier=>'F'
,p_column_label=>'Nombre'
,p_column_link=>'f?p=&APP_ID.:29:&SESSION.::&DEBUG.::P29_EQUIPO:#ID#'
,p_column_linktext=>'#NOMBRE#'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87976622885838604119)
,p_db_column_name=>'TIPO_EQUIPO_ID'
,p_display_order=>70
,p_column_identifier=>'G'
,p_column_label=>'Tipo Equipo'
,p_column_type=>'NUMBER'
,p_display_text_as=>'LOV_ESCAPE_SC'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_rpt_named_lov=>wwv_flow_imp.id(17289756602724474033)
,p_rpt_show_filter_lov=>'1'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87976622917686604120)
,p_db_column_name=>'SUB_TIPO_EQUIPO'
,p_display_order=>80
,p_column_identifier=>'H'
,p_column_label=>'Sub Tipo Equipo'
,p_column_type=>'STRING'
,p_display_text_as=>'LOV_ESCAPE_SC'
,p_heading_alignment=>'LEFT'
,p_rpt_named_lov=>wwv_flow_imp.id(17292525545179850352)
,p_rpt_show_filter_lov=>'1'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87976623088009604121)
,p_db_column_name=>'MARCA'
,p_display_order=>90
,p_column_identifier=>'I'
,p_column_label=>'Marca'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87976623137679604122)
,p_db_column_name=>'MODELO'
,p_display_order=>100
,p_column_identifier=>'J'
,p_column_label=>'Modelo'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87976623227945604123)
,p_db_column_name=>'ESTADO'
,p_display_order=>110
,p_column_identifier=>'K'
,p_column_label=>'Estado'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87976623340414604124)
,p_db_column_name=>'OBSERVACIONES'
,p_display_order=>120
,p_column_identifier=>'L'
,p_column_label=>'Observaciones'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87976623427006604125)
,p_db_column_name=>'NI_ANDE'
,p_display_order=>130
,p_column_identifier=>'M'
,p_column_label=>'Ni Ande'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87976623516104604126)
,p_db_column_name=>'SERIAL_NUMBER'
,p_display_order=>140
,p_column_identifier=>'N'
,p_column_label=>'Serial Number'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87976623680584604127)
,p_db_column_name=>'VERSION_HARDWARE'
,p_display_order=>150
,p_column_identifier=>'O'
,p_column_label=>'Version Hardware'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87976623772294604128)
,p_db_column_name=>'VERSION_SOFTWARE'
,p_display_order=>160
,p_column_identifier=>'P'
,p_column_label=>'Version Software'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87976623887314604129)
,p_db_column_name=>'VERSION_PATCH'
,p_display_order=>170
,p_column_identifier=>'Q'
,p_column_label=>'Version Patch'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87976623948012604130)
,p_db_column_name=>'IP_GESTION'
,p_display_order=>180
,p_column_identifier=>'R'
,p_column_label=>'Ip Gestion'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87976624039202604131)
,p_db_column_name=>'ALIMENTACION1_ID'
,p_display_order=>190
,p_column_identifier=>'S'
,p_column_label=>'Alimentacion1 Id'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87976624159785604132)
,p_db_column_name=>'ALIMENTACION2_ID'
,p_display_order=>200
,p_column_identifier=>'T'
,p_column_label=>'Alimentacion2 Id'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87976624211095604133)
,p_db_column_name=>'PROYECTO_ID'
,p_display_order=>210
,p_column_identifier=>'U'
,p_column_label=>'Proyecto Id'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87976624379323604134)
,p_db_column_name=>'FECHA_IMPLE'
,p_display_order=>220
,p_column_identifier=>'V'
,p_column_label=>'Fecha Imple'
,p_column_type=>'DATE'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87976624432409604135)
,p_db_column_name=>'ALTURA_U'
,p_display_order=>230
,p_column_identifier=>'W'
,p_column_label=>'Altura U'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87976624518412604136)
,p_db_column_name=>'POSICION'
,p_display_order=>240
,p_column_identifier=>'X'
,p_column_label=>'Posicion'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87976624620487604137)
,p_db_column_name=>'SITIO_ID'
,p_display_order=>250
,p_column_identifier=>'Y'
,p_column_label=>'Sitio Id'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87976624733825604138)
,p_db_column_name=>'CREADO_POR'
,p_display_order=>260
,p_column_identifier=>'Z'
,p_column_label=>'Creado Por'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87976624812467604139)
,p_db_column_name=>'CREADO_EL'
,p_display_order=>270
,p_column_identifier=>'AA'
,p_column_label=>'Creado El'
,p_column_type=>'DATE'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87976624912152604140)
,p_db_column_name=>'ACTUALIZADO_POR'
,p_display_order=>280
,p_column_identifier=>'AB'
,p_column_label=>'Actualizado Por'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(87976625038492604141)
,p_db_column_name=>'ACTUALIZADO_EL'
,p_display_order=>290
,p_column_identifier=>'AC'
,p_column_label=>'Actualizado El'
,p_column_type=>'DATE'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_rpt(
 p_id=>wwv_flow_imp.id(87989439225205887853)
,p_application_user=>'APXWS_DEFAULT'
,p_report_seq=>10
,p_report_alias=>'879894393'
,p_status=>'PUBLIC'
,p_is_default=>'Y'
,p_report_columns=>'ID:UNIDAD_ENCARGADA:RACK_ID:U:TIPO_RED:NOMBRE:TIPO_EQUIPO_ID:SUB_TIPO_EQUIPO:MARCA:MODELO:ESTADO:OBSERVACIONES:NI_ANDE:SERIAL_NUMBER:VERSION_HARDWARE:VERSION_SOFTWARE:VERSION_PATCH:IP_GESTION:ALIMENTACION1_ID:ALIMENTACION2_ID:PROYECTO_ID:FECHA_IMPLE:'
||'ALTURA_U:POSICION:SITIO_ID:CREADO_POR:CREADO_EL:ACTUALIZADO_POR:ACTUALIZADO_EL'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(200805781585123280031)
,p_plug_name=>'Breadcrumb'
,p_region_template_options=>'#DEFAULT#:t-BreadcrumbRegion--useBreadcrumbTitle'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>2531463326621247859
,p_plug_display_sequence=>10
,p_plug_display_point=>'REGION_POSITION_01'
,p_menu_id=>wwv_flow_imp.id(197180072443235446203)
,p_plug_source_type=>'NATIVE_BREADCRUMB'
,p_menu_template_id=>4072363345357175094
);
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(200805779978505280030)
,p_button_sequence=>10
,p_button_plug_id=>wwv_flow_imp.id(200805769845760280023)
,p_button_name=>'CREATE'
,p_button_action=>'REDIRECT_PAGE'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>4072362960822175091
,p_button_is_hot=>'Y'
,p_button_image_alt=>'&APP_TEXT$BTN_CREAR!RAW.'
,p_button_position=>'RIGHT_OF_IR_SEARCH_BAR'
,p_button_redirect_url=>'f?p=&APP_ID.:14:&SESSION.::&DEBUG.::P14_TITULO:Agregar equipo'
,p_security_scheme=>wwv_flow_imp.id(56843702980053272617)
);
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(202816056473491564096)
,p_button_sequence=>20
,p_button_plug_id=>wwv_flow_imp.id(200805769845760280023)
,p_button_name=>'IMPORTAR'
,p_button_action=>'REDIRECT_PAGE'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>4072362960822175091
,p_button_image_alt=>'&APP_TEXT$BTN_IMPORTAR_XLS!RAW.'
,p_button_position=>'RIGHT_OF_IR_SEARCH_BAR'
,p_button_redirect_url=>'f?p=&APP_ID.:6:&SESSION.::&DEBUG.:::'
,p_security_scheme=>wwv_flow_imp.id(56843702980053272617)
);
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(51494083749763384845)
,p_button_sequence=>30
,p_button_plug_id=>wwv_flow_imp.id(200805769845760280023)
,p_button_name=>'New'
,p_button_action=>'REDIRECT_PAGE'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>4072362960822175091
,p_button_image_alt=>'Racks'
,p_button_position=>'RIGHT_OF_IR_SEARCH_BAR'
,p_button_redirect_url=>'f?p=&APP_ID.:37:&SESSION.::&DEBUG.:::'
,p_required_patch=>wwv_flow_imp.id(197180071872965446203)
);
wwv_flow_imp_page.create_page_da_event(
 p_id=>wwv_flow_imp.id(200805780281165280030)
,p_name=>'Edit Report - Dialog Closed'
,p_event_sequence=>10
,p_triggering_element_type=>'REGION'
,p_triggering_region_id=>wwv_flow_imp.id(200805769845760280023)
,p_bind_type=>'bind'
,p_execution_type=>'IMMEDIATE'
,p_bind_event_type=>'apexafterclosedialog'
);
wwv_flow_imp_page.create_page_da_action(
 p_id=>wwv_flow_imp.id(200805780757967280031)
,p_event_id=>wwv_flow_imp.id(200805780281165280030)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_REFRESH'
,p_affected_elements_type=>'REGION'
,p_affected_region_id=>wwv_flow_imp.id(200805769845760280023)
,p_attribute_01=>'N'
);
wwv_flow_imp.component_end;
end;
/
