prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/user_interfaces.sql
@@application/shared_components/navigation/lists/access_control.sql
@@application/shared_components/navigation/lists/asistente_servicios.sql
@@application/shared_components/navigation/lists/wzrd_conexiones_wan.sql
@@application/shared_components/navigation/lists/navigation_menu.sql
@@application/shared_components/navigation/lists/navigation_bar.sql
@@application/shared_components/navigation/listentry.sql
@@application/shared_components/files/racks_css.sql
@@application/shared_components/files/racks_min_css.sql
@@application/shared_components/files/p400_vista_conexiones_js.sql
@@application/shared_components/files/p400_vista_conexiones_min_js.sql
@@application/shared_components/files/icons_app_icon_32_png.sql
@@application/shared_components/files/icons_app_icon_144_rounded_png.sql
@@application/shared_components/files/icons_app_icon_192_png.sql
@@application/shared_components/files/icons_app_icon_256_rounded_png.sql
@@application/shared_components/files/icons_app_icon_512_png.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/reader_rights.sql
@@application/shared_components/security/authorizations/jefatura_rights.sql
@@application/shared_components/security/authorizations/tecnico_rights.sql
@@application/shared_components/security/authorizations/implementador_rights.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/security/app_access_control/administrator.sql
@@application/shared_components/security/app_access_control/lector.sql
@@application/shared_components/security/app_access_control/tecnico.sql
@@application/shared_components/security/app_access_control/jefatura.sql
@@application/shared_components/security/app_access_control/implementador.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_items/depto_id.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/access_roles.sql
@@application/shared_components/user_interface/lovs/ciudad_nombre.sql
@@application/shared_components/user_interface/lovs/ciudad_nombre_compuesto.sql
@@application/shared_components/user_interface/lovs/email_username_format.sql
@@application/shared_components/user_interface/lovs/enlaces_logicos_nombre.sql
@@application/shared_components/user_interface/lovs/enlaces_wan.sql
@@application/shared_components/user_interface/lovs/equipos_nombre.sql
@@application/shared_components/user_interface/lovs/equipos_nombre_compuesto.sql
@@application/shared_components/user_interface/lovs/estado_enlace_fo.sql
@@application/shared_components/user_interface/lovs/estado_equipo.sql
@@application/shared_components/user_interface/lovs/grupo_red.sql
@@application/shared_components/user_interface/lovs/interface_duplex.sql
@@application/shared_components/user_interface/lovs/interface_modo.sql
@@application/shared_components/user_interface/lovs/interfaz_estado.sql
@@application/shared_components/user_interface/lovs/lov_sgt_ciudad.sql
@@application/shared_components/user_interface/lovs/lov_sgt_dpto.sql
@@application/shared_components/user_interface/lovs/lov_sgt_racks_filtrado.sql
@@application/shared_components/user_interface/lovs/lov_sgt_salas.sql
@@application/shared_components/user_interface/lovs/lov_sgt_sitios.sql
@@application/shared_components/user_interface/lovs/lov_sgt_zonas.sql
@@application/shared_components/user_interface/lovs/lov_sitios_sf.sql
@@application/shared_components/user_interface/lovs/lov_tipo_equipos.sql
@@application/shared_components/user_interface/lovs/lov_tipo_interfaz.sql
@@application/shared_components/user_interface/lovs/lov_uni_encar.sql
@@application/shared_components/user_interface/lovs/modo_fo.sql
@@application/shared_components/user_interface/lovs/nivel_prioridad.sql
@@application/shared_components/user_interface/lovs/racks_nombre_compuesto.sql
@@application/shared_components/user_interface/lovs/racks_nombres.sql
@@application/shared_components/user_interface/lovs/salas_nombre.sql
@@application/shared_components/user_interface/lovs/sgt_enlaces_fo_nombre.sql
@@application/shared_components/user_interface/lovs/sgt_interfaces_nombre.sql
@@application/shared_components/user_interface/lovs/sgt_servicios_nombre.sql
@@application/shared_components/user_interface/lovs/sgt_sitios_siglas.sql
@@application/shared_components/user_interface/lovs/sgt_tipo_cable_nombre.sql
@@application/shared_components/user_interface/lovs/sub_tipo_equipo.sql
@@application/shared_components/user_interface/lovs/tipo_cable.sql
@@application/shared_components/user_interface/lovs/tipo_conector.sql
@@application/shared_components/user_interface/lovs/tipo_enlace.sql
@@application/shared_components/user_interface/lovs/tipo_fo.sql
@@application/shared_components/user_interface/lovs/tipo_lt.sql
@@application/shared_components/user_interface/lovs/tipo_red.sql
@@application/shared_components/user_interface/lovs/tipo_sitio.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/globalization/translations.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/security/authentications/oracle_apex_accounts.sql
@@application/shared_components/data_loads/agregar_interfaces_dl.sql
@@application/shared_components/data_loads/replace_interfaces_dl.sql
@@application/shared_components/data_loads/enlaces_fo_dataload.sql
@@application/shared_components/data_loads/enlaces_tramos_dataload.sql
@@application/shared_components/data_loads/sgt_dl_equipos.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00003.sql
@@application/pages/page_00004.sql
@@application/pages/page_00005.sql
@@application/pages/page_00006.sql
@@application/pages/page_00007.sql
@@application/pages/page_00008.sql
@@application/pages/page_00009.sql
@@application/pages/page_00010.sql
@@application/pages/page_00011.sql
@@application/pages/page_00012.sql
@@application/pages/page_00013.sql
@@application/pages/page_00014.sql
@@application/pages/page_00015.sql
@@application/pages/page_00016.sql
@@application/pages/page_00017.sql
@@application/pages/page_00018.sql
@@application/pages/page_00019.sql
@@application/pages/page_00020.sql
@@application/pages/page_00021.sql
@@application/pages/page_00022.sql
@@application/pages/page_00023.sql
@@application/pages/page_00024.sql
@@application/pages/page_00025.sql
@@application/pages/page_00026.sql
@@application/pages/page_00027.sql
@@application/pages/page_00028.sql
@@application/pages/page_00029.sql
@@application/pages/page_00030.sql
@@application/pages/page_00031.sql
@@application/pages/page_00032.sql
@@application/pages/page_00033.sql
@@application/pages/page_00034.sql
@@application/pages/page_00035.sql
@@application/pages/page_00036.sql
@@application/pages/page_00037.sql
@@application/pages/page_00038.sql
@@application/pages/page_00039.sql
@@application/pages/page_00040.sql
@@application/pages/page_00041.sql
@@application/pages/page_00042.sql
@@application/pages/page_00043.sql
@@application/pages/page_00044.sql
@@application/pages/page_00045.sql
@@application/pages/page_00046.sql
@@application/pages/page_00047.sql
@@application/pages/page_00050.sql
@@application/pages/page_00051.sql
@@application/pages/page_00052.sql
@@application/pages/page_00053.sql
@@application/pages/page_00054.sql
@@application/pages/page_00100.sql
@@application/pages/page_00200.sql
@@application/pages/page_00400.sql
@@application/pages/page_00401.sql
@@application/pages/page_00402.sql
@@application/pages/page_00403.sql
@@application/pages/page_00404.sql
@@application/pages/page_00410.sql
@@application/pages/page_00420.sql
@@application/pages/page_09999.sql
@@application/pages/page_10000.sql
@@application/pages/page_10010.sql
@@application/pages/page_10011.sql
@@application/pages/page_10012.sql
@@application/pages/page_10013.sql
@@application/pages/page_10014.sql
@@application/deployment/definition.sql
@@application/deployment/install/install_crear_funciones.sql
@@application/deployment/install/install_crear_pkg.sql
@@application/deployment/install/install_crear_seq.sql
@@application/deployment/install/install_crear_tablas.sql
@@application/deployment/install/install_crear_types.sql
@@application/deployment/install/install_crear_vistas.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
